name: No se amor
favicon: null
layout_spectrum: 0.8519874077755958
typography_spectrum: 0.31097638444043696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09779533208347857
  lightness: 0.30379041959531605
  saturation: 0.31068902369588614
  rhythmicContrast: 0.7197728399187326
purpose: []
